#ifndef CORELIBRARY_GLOBAL_H
#define CORELIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CORELIBRARY_LIBRARY)
#  define CORELIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CORELIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CORELIBRARY_GLOBAL_H
