#ifndef DOWNLOADCLIENT_GLOBAL_H
#define DOWNLOADCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DOWNLOADCLIENT_LIBRARY)
#  define DOWNLOADCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DOWNLOADCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DOWNLOADCLIENT_GLOBAL_H
