#ifndef DOWNLOADSERVER_GLOBAL_H
#define DOWNLOADSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DOWNLOADSERVER_LIBRARY)
#  define DOWNLOADSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DOWNLOADSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DOWNLOADCLIENT_GLOBAL_H
