#ifndef COMMUNICATIONSERVER_GLOBAL_H
#define COMMUNICATIONSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMUNICATIONSERVER_LIBRARY)
#  define COMMUNICATIONSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMUNICATIONSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMUNICATIONSERVER_GLOBAL_H
