#ifndef COMMUNICATIONCLIENT_GLOBAL_H
#define COMMUNICATIONCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMUNICATIONCLIENT_LIBRARY)
#  define COMMUNICATIONCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMUNICATIONCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMUNICATIONCLIENT_GLOBAL_H
